CREATE TABLE IF NOT EXISTS tag (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	description VARCHAR(450) NOT NULL,
	date_created TIMESTAMPTZ NULL,
	date_updated TIMESTAMPTZ NULL,
	deleted_fg BOOL NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS pk_idx_tag_title ON topic (title);

GRANT SELECT, INSERT, UPDATE ON TABLE tag TO blog;